### ISSUE TITLE
Maximum dict size leads to unexpected behaviour

### ISSUE THREAD

**Issue by FelixMoelder** [andrewnester/rust-jsonm#1]
Hey there,

first of all thanks for building this crate.

When applying jsonm to our data we found an issue related to the [maximum dict size](https://github.com/andrewnester/rust-jsonm/blob/52910b8793172aff38adca07dd8c9522a82633b2/src/packer.rs#L68) causing mismatches of dict entries.
For some reason the `dict_index` will be set to `MIN_DICT_INDEX` overwriting existing entries when `max_dict_size` is exceeded (see [L309](https://github.com/andrewnester/rust-jsonm/blob/52910b8793172aff38adca07dd8c9522a82633b2/src/packer.rs#L309)).

As this leads to non-deterministic results the execution should fail and an error be returned.

But what I'm wondering is, why even a maximum dict size needs to be defined. I did not find a reason for not just increasing the index being only limited by the maximum `u64` value.

**Comment by andrewnester** [comment]
Hi @FelixMoelder !

Thanks for the reporting the issue.

The value is used to define a maximum size of the dictionary being used, so it does not consume lots of memory. 
For example, having maximum dict size set at maximum `u64` would mean that in the application which does a lot of packing / unpacking it will grow up to 18446 TB which will definitely consume all the memory.

So limitation is necessary. But mechanism to reuse old index supposed to be working, so I guess there is a bug there.

There is a set of tests covering the cases when object you're packing is larger then dictionary size, for example
https://github.com/andrewnester/rust-jsonm/blob/master/tests/test_packer.rs#L558

So I wonder when exactly did you see your issue occur?
Could you please provide a test case when the issue happens or set of data for which you can see this issue happening?

Thanks a lot!

**Comment by andrewnester** [comment]
I guess the issue might be regarding packing complex objects.
I see that in original package it was fixed
https://github.com/lennartcl/jsonm/commit/4b7db8b4da948f34e25a16643d279aaef5fc7073

I will work on the porting this changes to this package

**Comment by andrewnester** [comment]
Sorry for 0 updates for this issue, I didn't have yet chance to look at it, will try to do this before end of the 2021 still, fingers crossed

**Comment by andrewnester** [comment]
This should be fixed now and available in 0.2.0 version, thanks again for the report

https://crates.io/crates/jsonm/0.2.0

**Comment by FelixMoelder** [comment]
Perfect, thanks for fixing this!

**Comment by fxwiegand** [comment]
> This should be fixed now and available in 0.2.0 version, thanks again for the report
> 
> https://crates.io/crates/jsonm/0.2.0

Thanks a lot for the fix! Our current workaround was to increase the maximum dict size with `packer.set_max_dict_size(100000)` and of course increase it correspondingly in the unpacker. As far as i understand the fix adds `MAX_PACK_COMPLEX_OBJECT_SIZE` to limit the complexity/depth? of the objects. What would happen if we exceed that limitation?

**Comment by andrewnester** [comment]
@fxwiegand there are actually more changes than that. There is some refactoring for `memoise` function (previously `add_to_dict`) which is responsible for storing certain memoised data. Initial bug was likely caused by some keys being reused wrong due to the way packer worked with keys. Now instead of just storing string value in `memoised` map[, `MemoObject` is stored which contains the stringifiled value of memoised object and the corresponding key in memoised_map / memoised_object_map so that they can be cleaned and reused properly.
