### ISSUE TITLE
error "index out of bounds: the len is 0 but the index is 0"

### ISSUE THREAD

**Issue by fish-sammy** [andrewnester/rust-jsonm#2]
Hi, I'm trying to use the library to unpack the attached data and I am getting the error `thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/sammyliu/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonm-0.1.4/src/unpacker.rs:161:27`. The same data unpacks fine with the js library though. Any idea?

[packed-data.json.zip](https://github.com/andrewnester/rust-jsonm/files/5650536/packed-data.json.zip)

**Comment by andrewnester** [comment]
This should be fixed by this commit and available in 0.2.0 version
https://github.com/andrewnester/rust-jsonm/commit/1f2ec252980f58bc7e94c6602c8c3521ef0a1ca2
